from __future__ import annotations

from .dti import (
    bvec_reorientation,
    censor_dwi,
    concat_dewarp,
    deformation_gradient_optimized,
    dipy_dti_recon,
    distortion_correct_bvecs,
    dti_numpy_to_image,
    dti_reg,
    dti_template,
    dwi_closest_peak_tracking,
    dwi_deterministic_tracking,
    dwi_streamline_connectivity,
    dwi_streamline_pairwise_connectivity,
    efficient_dwi_fit,
    efficient_dwi_fit_voxelwise,
    efficient_tensor_fit,
    generate_voxelwise_bvecs,
    get_average_dwi_b0,
    get_dti,
    impute_dwi,
    impute_fa,
    joint_dti_recon,
    mc_denoise,
    merge_dwi_data,
    read_ants_transforms_to_numpy,
    repair_bvecs,
    transform_and_reorient_dti,
    triangular_to_tensor,
    trim_dti_mask,
    write_bvals_bvecs,
)
from .fmri import (
    PerAF,
    alff_image,
    alffmap,
    calculate_trimmed_mean,
    compute_PerAF_voxel,
    copy_spatial_metadata_from_3d_to_4d,
    despike_time_series,
    despike_time_series_afni,
    estimate_optimal_pca_components,
    get_average_rsf,
    plot_spec,
    resting_state_fmri_networks,
    spec_ci,
    spec_pgram,
    spec_taper,
    timeseries_reg,
    timeseries_transform,
)
from .metrics import (
    ants_to_nibabel_affine,
    apply_transforms_mixed_interpolation,
    calculate_loop_scores,
    calculate_loop_scores_full,
    convert_np_in_dict,
    crop_mcimage,
    dict_to_dataframe,
    dvars,
    flatten_time_series,
    foreground_background_snr,
    get_antsimage_keys,
    hierarchical_modality_summary,
    image_write_with_thumbnail,
    impute_timeseries,
    loop_timeseries_censoring,
    mask_snr,
    middle_slice_snr,
    quantile_snr,
    remove_elements_from_list,
    remove_elements_from_numpy_array,
    remove_volumes_from_timeseries,
    score_fmri_censoring,
    segment_timeseries_by_bvalue,
    segment_timeseries_by_meanvalue,
    shorten_pymm_names,
    shorten_pymm_names2,
    slice_snr,
    to_nibabel,
    tsnr,
)
from .neuromelanin import (
    neuromelanin,
    tra_initializer,
)
from .perfusion import (
    bold_perfusion,
    bold_perfusion_minimal,
    calculate_CBF,
    pet3d_summary,
    warn_if_small_mask,
)
from .registration import (
    dewarp_imageset,
    mc_reg,
)
from .segmentation import (
    enantiomorphic_filling_without_mask,
    map_scalar_to_labels,
)
from .super_resolution import (
    down2iso,
    super_res_mcimage,
    t1w_super_resolution_with_hemispheres,
)
from .templates import (
    get_data,
    get_models,
)
from .wmh import (
    augment_image,
    boot_wmh,
    wmh,
)

__all__ = [
    # templates
    "get_data",
    "get_models",
    # registration
    "apply_transforms_mixed_interpolation",
    "bvec_reorientation",
    "concat_dewarp",
    "deformation_gradient_optimized",
    "dewarp_imageset",
    "distortion_correct_bvecs",
    "dti_reg",
    "dti_template",
    "generate_voxelwise_bvecs",
    "get_average_dwi_b0",
    "get_average_rsf",
    "mc_reg",
    "read_ants_transforms_to_numpy",
    "timeseries_reg",
    "timeseries_transform",
    "tra_initializer",
    "transform_and_reorient_dti",
    # segmentation
    "augment_image",
    "boot_wmh",
    "crop_mcimage",
    "enantiomorphic_filling_without_mask",
    "map_scalar_to_labels",
    "segment_timeseries_by_bvalue",
    "segment_timeseries_by_meanvalue",
    "trim_dti_mask",
    "warn_if_small_mask",
    "wmh",
    # metrics
    "get_antsimage_keys",
    "dict_to_dataframe",
    "image_write_with_thumbnail",
    "shorten_pymm_names",
    "shorten_pymm_names2",
    "hierarchical_modality_summary",
    "to_nibabel",
    "ants_to_nibabel_affine",
    "convert_np_in_dict",
    "tsnr",
    "dvars",
    "slice_snr",
    "middle_slice_snr",
    "foreground_background_snr",
    "quantile_snr",
    "mask_snr",
    "flatten_time_series",
    "calculate_loop_scores",
    "calculate_loop_scores_full",
    "remove_elements_from_numpy_array",
    "remove_volumes_from_timeseries",
    "remove_elements_from_list",
    "impute_timeseries",
    "loop_timeseries_censoring",
    "score_fmri_censoring",
    # dti
    "write_bvals_bvecs",
    "repair_bvecs",
    "triangular_to_tensor",
    "dti_numpy_to_image",
    "get_dti",
    "impute_fa",
    "impute_dwi",
    "censor_dwi",
    "merge_dwi_data",
    "mc_denoise",
    "efficient_tensor_fit",
    "efficient_dwi_fit",
    "efficient_dwi_fit_voxelwise",
    "dipy_dti_recon",
    "joint_dti_recon",
    "dwi_deterministic_tracking",
    "dwi_closest_peak_tracking",
    "dwi_streamline_pairwise_connectivity",
    "dwi_streamline_connectivity",
    # fmri
    "spec_taper",
    "spec_ci",
    "plot_spec",
    "spec_pgram",
    "alffmap",
    "alff_image",
    "compute_PerAF_voxel",
    "calculate_trimmed_mean",
    "PerAF",
    "despike_time_series_afni",
    "despike_time_series",
    "copy_spatial_metadata_from_3d_to_4d",
    "estimate_optimal_pca_components",
    "resting_state_fmri_networks",
    # neuromelanin
    "neuromelanin",
    # perfusion
    "calculate_CBF",
    "bold_perfusion_minimal",
    "bold_perfusion",
    "pet3d_summary",
    # super_resolution
    "down2iso",
    "super_res_mcimage",
    "t1w_super_resolution_with_hemispheres",
]
