import os
from pathlib import Path
import pandas as pd

def parse_antsxbids_layout(bids_root):
    """
    Parses a BIDS directory generated by antsxbids.
    Returns a pandas DataFrame where each row is a unique Session.
    """
    bids_path = Path(bids_root)
    if not bids_path.exists():
        raise FileNotFoundError(f"Directory not found: {bids_root}")

    # Use glob matching for robustness
    subjects = sorted([d for d in bids_path.glob("sub*") if d.is_dir()])
    
    sessions_data = []

    for sub_dir in subjects:
        # CHANGED: Use the full folder name as the ID (e.g. 'sub-211239')
        sub_id = sub_dir.name
        
        # Find sessions
        sessions = sorted([d for d in sub_dir.glob("ses*") if d.is_dir()])
        
        for ses_dir in sessions:
            # CHANGED: Use the full folder name as the ID (e.g. 'ses-20230405')
            ses_id = ses_dir.name
            
            # Initialize dict for this session
            data = {
                'subjectID': sub_id,
                'date': ses_id, 
                'session_path': str(ses_dir)
            }

            # 1. Anatomy (T1w, FLAIR)
            anat_dir = ses_dir / 'anat'
            if anat_dir.exists():
                t1s = sorted(list(anat_dir.glob("*T1w.nii.gz")))
                flairs = sorted(list(anat_dir.glob("*FLAIR.nii.gz")))
                
                if t1s:
                    data['t1_filename'] = str(t1s[0])
                if flairs:
                    data['flair_filename'] = str(flairs[0])

            # 2. DWI
            dwi_dir = ses_dir / 'dwi'
            dwi_files = []
            if dwi_dir.exists():
                dwi_files = sorted([str(p) for p in dwi_dir.glob("*.nii.gz")])
            data['dti_filenames'] = dwi_files

            # 3. Functional
            func_dir = ses_dir / 'func'
            rsf_files = []
            if func_dir.exists():
                rsf_files = sorted([str(p) for p in func_dir.glob("*bold.nii.gz")])
            data['rsf_filenames'] = rsf_files

            # 4. Neuromelanin
            nm_dir = ses_dir / 'melanin'
            nm_files = []
            if nm_dir.exists():
                nm_files = sorted([str(p) for p in nm_dir.glob("*NM.nii.gz")])
            data['nm_filenames'] = nm_files

            # 5. Perfusion (ASL) - Placeholder logic, assuming 'perf' folder
            perf_dir = ses_dir / 'perf'
            if perf_dir.exists():
                # Grab the first available ASL file
                perfs = sorted(list(perf_dir.glob("*.nii.gz")))
                if perfs:
                    data['perf_filename'] = str(perfs[0])

            # 6. PET (pet3d) - Placeholder logic, assuming 'pet' folder
            pet_dir = ses_dir / 'pet'
            if pet_dir.exists():
                # Grab the first available PET file
                pets = sorted(list(pet_dir.glob("*.nii.gz")))
                if pets:
                    data['pet3d_filename'] = str(pets[0])

            # Only add if we have a T1
            if 't1_filename' in data:
                sessions_data.append(data)

    return pd.DataFrame(sessions_data)