import os
from pathlib import Path
import pandas as pd


def _sorted_glob(dirpath: Path, patterns):
    out = []
    for pat in patterns:
        out.extend(list(dirpath.glob(pat)))
    return sorted([str(p) for p in out if p.is_file()])


def _select_first(files, preferred_substrings=None):
    """Select a single file from a candidate list.

    If preferred_substrings is provided, the first file whose basename contains
    any preferred substring (case-insensitive) is returned. Otherwise the first
    file in sorted order is returned.
    """
    if not files:
        return None
    if preferred_substrings:
        lowered = [s.lower() for s in preferred_substrings]
        for f in files:
            b = os.path.basename(f).lower()
            if any(s in b for s in lowered):
                return f
    return files[0]

def parse_antsxbids_layout(bids_root):
    """
    Parses a BIDS directory generated by antsxbids.
    Returns a pandas DataFrame where each row is a unique Session.
    """
    bids_path = Path(bids_root)
    if not bids_path.exists():
        raise FileNotFoundError(f"Directory not found: {bids_root}")

    # Use glob matching for robustness
    subjects = sorted([d for d in bids_path.glob("sub*") if d.is_dir()])
    
    sessions_data = []

    for sub_dir in subjects:
        sub_id = sub_dir.name
        
        sessions = sorted([d for d in sub_dir.glob("ses*") if d.is_dir()])
        
        for ses_dir in sessions:
            ses_id = ses_dir.name
            
            data = {
                'subjectID': sub_id,
                'date': ses_id, 
                'session_path': str(ses_dir)
            }

            # 1. Anatomy (T1w, FLAIR)
            anat_dir = ses_dir / 'anat'
            t1_files = []
            if anat_dir.exists():
                t1_files = _sorted_glob(anat_dir, ["*T1w.nii.gz", "*T1w.nii"])
                flair_files = _sorted_glob(anat_dir, ["*FLAIR.nii.gz", "*FLAIR.nii"])
                t2w_files = _sorted_glob(anat_dir, ["*T2w.nii.gz", "*T2w.nii"])

                data['flair_filenames'] = flair_files
                data['t2w_filenames'] = t2w_files

                # Back-compat singletons
                data['flair_filename'] = _select_first(flair_files)
                data['t2w_filename'] = _select_first(t2w_files)
            
            data['t1_filenames'] = t1_files # Store ALL T1s

            # 2. DWI
            dwi_dir = ses_dir / 'dwi'
            dwi_files = []
            if dwi_dir.exists():
                dwi_files = _sorted_glob(dwi_dir, ["*.nii.gz", "*.nii"])
            data['dti_filenames'] = dwi_files

            # 3. Functional
            func_dir = ses_dir / 'func'
            rsf_files = []
            if func_dir.exists():
                rsf_files = _sorted_glob(func_dir, ["*bold.nii.gz", "*bold.nii"])
            data['rsf_filenames'] = rsf_files

            # 4. Neuromelanin
            nm_dir = ses_dir / 'melanin'
            nm_files = []
            if nm_dir.exists():
                nm_files = _sorted_glob(nm_dir, ["*NM.nii.gz", "*NM.nii"])
            data['nm_filenames'] = nm_files

            # 5. Perfusion
            perf_dir = ses_dir / 'perf'
            if perf_dir.exists():
                perf_files = _sorted_glob(perf_dir, ["*.nii.gz", "*.nii"])
                data['perf_filenames'] = perf_files
                # Prefer ASL-like series if present.
                data['perf_filename'] = _select_first(perf_files, preferred_substrings=["asl", "cbf", "perfusion"]) 

            # 6. PET
            pet_dir = ses_dir / 'pet'
            if pet_dir.exists():
                pet_files = _sorted_glob(pet_dir, ["*.nii.gz", "*.nii"])
                data['pet3d_filenames'] = pet_files
                # Prefer typical PET series names if present.
                data['pet3d_filename'] = _select_first(pet_files, preferred_substrings=["pet", "suv", "suvr", "dyn", "static"]) 

            # Only add if we have at least one T1
            if data['t1_filenames']:
                sessions_data.append(data)

    return pd.DataFrame(sessions_data)