import os
from pathlib import Path
import pandas as pd

def parse_antsxbids_layout(bids_root):
    """
    Parses a BIDS directory generated by antsxbids.
    Returns a pandas DataFrame where each row is a unique Session.
    """
    bids_path = Path(bids_root)
    if not bids_path.exists():
        raise FileNotFoundError(f"Directory not found: {bids_root}")

    # Use glob matching for robustness
    subjects = sorted([d for d in bids_path.glob("sub*") if d.is_dir()])
    
    sessions_data = []

    for sub_dir in subjects:
        # Robust split for subject ID
        parts = sub_dir.name.split("-")
        if len(parts) > 1:
            sub_id = parts[1]
        else:
            sub_id = parts[0]
        
        # Find sessions
        sessions = sorted([d for d in sub_dir.glob("ses*") if d.is_dir()])
        
        for ses_dir in sessions:
            ses_parts = ses_dir.name.split("-")
            if len(ses_parts) > 1:
                ses_id = ses_parts[1]
            else:
                ses_id = ses_parts[0]
            
            # Initialize dict for this session
            data = {
                'subjectID': sub_id,
                'date': ses_id, # antsxbids usually puts date in ses
                'session_path': str(ses_dir)
            }

            # 1. Anatomy (T1w, FLAIR)
            anat_dir = ses_dir / 'anat'
            if anat_dir.exists():
                t1s = sorted(list(anat_dir.glob("*T1w.nii.gz")))
                flairs = sorted(list(anat_dir.glob("*FLAIR.nii.gz")))
                
                if t1s:
                    data['t1_filename'] = str(t1s[0])
                if flairs:
                    data['flair_filename'] = str(flairs[0])

            # 2. DWI
            dwi_dir = ses_dir / 'dwi'
            dwi_files = []
            if dwi_dir.exists():
                dwi_files = sorted([str(p) for p in dwi_dir.glob("*.nii.gz")])
            data['dti_filenames'] = dwi_files

            # 3. Functional
            func_dir = ses_dir / 'func'
            rsf_files = []
            if func_dir.exists():
                rsf_files = sorted([str(p) for p in func_dir.glob("*bold.nii.gz")])
            data['rsf_filenames'] = rsf_files

            # 4. Neuromelanin
            nm_dir = ses_dir / 'melanin'
            nm_files = []
            if nm_dir.exists():
                nm_files = sorted([str(p) for p in nm_dir.glob("*NM.nii.gz")])
            data['nm_filenames'] = nm_files

            # Only add if we have a T1
            if 't1_filename' in data:
                sessions_data.append(data)

    return pd.DataFrame(sessions_data)
